
services:
  api:
    build:
      context: .
      dockerfile: ./docker/api.dockerfile
    tty: true
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
  db:
    build:
      context: ./docker/
      dockerfile: db.dockerfile
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/initdb:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:


secrets:
  db-password:
    file: db/password.txt
